language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodinlive/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodinlive/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-790333672162"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
